# Use an official Node.js runtime as a parent image
FROM node:18

# Set the working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY ./package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY ./ .

# Expose port (adjust as needed for your application)
EXPOSE 5001

# Command to run the application
CMD ["npm", "start"]
